#!/usr/bin/bash

GOSRCDIR="/workSpace/go/src"
GHPROGDIR="/GitHub/go/programs"
DIFFOUT=$(diff -r $GOSRCDIR $GHPROGDIR | sed -e 's/Only in //g;s/: /\//g;s/\.\///g')

if [[ -n $DIFFOUT ]]
then
	rsync -avu --delete $GOSRCDIR/* $GHPROGDIR/
	cd /GitHub/go
	gitadd
else
	echo "Yo Bingo! I've got nothing, Do some code and come back !!!"
fi
